exyte/Macaw

Example/Example/Examples/Animations/AnimationsView.swift
MacawTests/Animation/CombineAnimationTests.swift
MacawTests/Animation/ControlStatesTests.swift
MacawTests/Animation/SequenceAnimationTests.swift
Source/animation/AnimationProducer.swift
Source/animation/types/ContentsAnimation.swift
Source/animation/types/OpacityAnimation.swift
Source/animation/types/ShapeAnimation.swift
Source/animation/types/TransformAnimation.swift
Source/animation/types/animation_generators/Cache/TransformHashable.swift
Source/render/ImageRenderer.swift
Source/render/RenderUtils.swift
Source/svg/SVGParser.swift
Source/svg/SVGView.swift
Source/views/MacawView.swift

issue Fix Macaw.xcodeproj warnings #90

Fixed all warnings in project.

---

Example/Podfile.lock
Macaw.xcodeproj/project.pbxproj
MacawTests/Bounds/NodeBoundsTests.swift
Source/model/draw/LinearGradient.swift
Source/model/draw/RadialGradient.swift
Source/model/geom2d/Arc.swift
Source/model/geom2d/Circle.swift
Source/model/geom2d/Ellipse.swift
Source/model/geom2d/Line.swift
Source/model/geom2d/Path.swift
Source/model/geom2d/Point.swift
Source/model/geom2d/Polygon.swift
Source/model/geom2d/Polyline.swift
Source/model/geom2d/Rect.swift
Source/model/geom2d/RoundRect.swift
Source/model/scene/Group.swift
Source/model/scene/Image.swift
Source/model/scene/Shape.swift
Source/render/ImageRenderer.swift
Source/svg/SVGParser.swift
Source/svg/SVGParserRegexHelper.swift

- Bounds() test
- Implementation for several locuses/nodes 
- Fix SVG Parser

Tests bounds

---

Source/model/scene/Image.swift

Does the srcVar has to be explicitly changed when loading the image like it was doing before?

Added jpg support.

---

Source/model/scene/Image.swift
Source/render/RenderUtils.swift
Source/svg/SVGParser.swift

Fix warnings for substring method deprecated

---

MacawTests/MacawSVGTests.swift
Source/svg/SVGSerializer.swift

For details see https://www.w3.org/TR/SVG/implnote.html#ArcImplementationNotes

Implement arc to SVG serialization

---

Source/svg/SVGParser.swift

- Pass text anchor
- Pass stroke

Fix SVG parser for text anchor and stroke in text elements

---

Source/model/scene/Text.swift

Text bounds fix

---

README.md

This fixed a problem with the URL displaying

Removed white space in README.md

---

.travis.yml
Source/render/RenderUtils.swift

#276
* Use MBezierPath to create bezier path
* AffineTransform is different for iOS and macOS

macOS doesn’t have UIBezierPath

---

Source/svg/SVGParser.swift

там я добавила гард, и все строчки просто сдвинулись - я ничего не меняла. только добавила проверку сверху метода

Fix #309: Style attribute "display" is being ignored

---

Source/svg/SVGParser.swift

Fix image clip path

---

Source/svg/SVGParser.swift

Fix transform on clipped images

---

Source/render/RenderUtils.swift

This is not only better style, but also the other way did not work.  Helvetica was always displayed.

Moved lowercasing as to not be destructive

---

Source/svg/SVGParser.swift

Usually multiline text is represented by multiple tspans, one for each line, and every tspan except the first one is positioned using dx and dy offsets. Although this fix doesn't fully support all dx/dy values, allowed in SVG by HTML 5 standard, such as number sequence, but still allows better rendering for multiline text.

Respect dx/dy attributes and calculate node position more precisely

---

Macaw.xcodeproj/project.pbxproj
MacawTests/MacawSVGTests.swift
MacawTests/w3cSVGTests/color-prop-04-t-manual.reference
MacawTests/w3cSVGTests/color-prop-04-t-manual.svg
Source/svg/SVGConstants.swift
Source/svg/SVGParser.swift

wip on Fix 387 - add "system" color support for SVG parser

---

Macaw.xcodeproj/project.pbxproj

Added supported platform in iOS target for Catalyst support

Added supported platform - macOS

---

Macaw.xcodeproj/project.pbxproj

This fixes a typo in #614 and enables Catalyst support (fixes #610)

Enable Catalyst support

---

Source/render/NodeRenderer.swift
Source/svg/SVGParser.swift

Fix some small formatting issues for readability + gradient stops fix

Svg parser fixes

---

Source/svg/SVGParser.swift

Small fix for crash on parsing pattern

Fix crash in parsing pattern

---

README.md
README_zh.md

update ios support to 9.0 (fixes #698)
